baseURL = "https://gofhir.github.io/fhirpath/"
title = "FHIRPath Go"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableRobotsTXT = true
enableGitInfo = true

disableKinds = ["taxonomy", "term"]

pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsStyle = "tango"

[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[markup]
[markup.goldmark]
  [markup.goldmark.parser.attribute]
  block = true
  [markup.goldmark.renderer]
  unsafe = true
[markup.highlight]
  style = "tango"
  noClasses = false

[outputs]
home = ["HTML", "RSS"]
section = ["HTML", "print", "RSS"]

# Languages (i18n)
[languages]
[languages.en]
  languageName = "English"
  contentDir = "content/en"
  weight = 1
  [languages.en.params]
  description = "A complete FHIRPath 2.0 expression evaluator for FHIR resources in Go"

[languages.es]
  languageName = "Espa√±ol"
  contentDir = "content/es"
  weight = 2
  [languages.es.params]
  description = "Un evaluador completo de expresiones FHIRPath 2.0 para recursos FHIR en Go"

[params]
version = "1.0.2"
version_menu = "Releases"
archived_version = false

github_repo = "https://github.com/gofhir/fhirpath"
github_project_repo = "https://github.com/gofhir/fhirpath"
github_subdir = "docs"
github_branch = "main"

offlineSearch = true
offlineSearchMaxResults = 25
offlineSearchSummaryLength = 200

prism_syntax_highlighting = false

[params.copyright]
  authors = "Roberto Araneda"
  from_year = 2025

[params.ui]
  breadcrumb_disable = false
  navbar_logo = true
  navbar_translucent_over_cover_disable = false
  sidebar_menu_compact = false
  sidebar_menu_foldable = true
  sidebar_search_disable = false
  showLightDarkModeMenu = true

[params.ui.feedback]
  enable = true
  yes = 'Glad to hear it! Please <a href="https://github.com/gofhir/fhirpath/issues/new">tell us how we can improve</a>.'
  no = 'Sorry to hear that. Please <a href="https://github.com/gofhir/fhirpath/issues/new">tell us how we can improve</a>.'

[params.ui.readingtime]
  enable = true

[[params.links.user]]
  name = "GitHub Discussions"
  url = "https://github.com/gofhir/fhirpath/discussions"
  icon = "fa fa-comments"
  desc = "Ask questions and get help"

[[params.links.developer]]
  name = "GitHub"
  url = "https://github.com/gofhir/fhirpath"
  icon = "fab fa-github"
  desc = "Development takes place here!"

[[params.links.developer]]
  name = "Go Package"
  url = "https://pkg.go.dev/github.com/gofhir/fhirpath"
  icon = "fa-solid fa-cube"
  desc = "Go documentation on pkg.go.dev"

[menu]
[[menu.main]]
  name = "Documentation"
  weight = 10
  url = "/docs/"

[[menu.main]]
  name = "pkg.go.dev"
  weight = 30
  url = "https://pkg.go.dev/github.com/gofhir/fhirpath"
  pre = "<i class='fa-solid fa-arrow-up-right-from-square'></i>"

[[menu.main]]
  name = "GitHub"
  weight = 40
  url = "https://github.com/gofhir/fhirpath"
  pre = "<i class='fab fa-github'></i>"

[module]
proxy = "direct"
[module.hugoVersion]
  extended = true
  min = "0.110.0"
[[module.imports]]
  path = "github.com/google/docsy"
  disable = false
